# Generated by Django 6.0.6 on 2026-06-12 09:19

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_newsarticle_author_name_newsarticle_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
